const {test,expect} = require('@playwright/test')

test('Login Test autogenerated by Playwright', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div').filter({ hasText: /^Dashboard$/ }).click();
  await page.locator('span').filter({ hasText: 'Varad Gaonkar' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});